language: node_js

before_script:
  - cp test/knexfile.js.dist test/knexfile.js
  - psql -U postgres -c 'create database "bookshelf-mask";'

node_js:
  - "4"
  - "5"
  - "6"

after_success:
  - npm run coveralls

sudo: false
